# Generated by Django 3.1 on 2020-08-17 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=10)),
                ('time_spent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('right_labels', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('played_times', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('email_errors', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('file_errors', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('conversation_errors', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('site_errors', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'case'),
                'unique_together': {('user', 'case')},
            },
        ),
    ]
