# Generated by Django 3.1 on 2020-11-04 15:36

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20200909_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelscore',
            name='played_times',
        ),
        migrations.AddField(
            model_name='levelscore',
            name='played',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 11, 4, 15, 36, 55, 458442, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='levelscore',
            name='conversation_errors',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='levelscore',
            name='email_errors',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='levelscore',
            name='file_errors',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='levelscore',
            name='site_errors',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
